@baseUrl = http://localhost:8080

### 幻读测试 SELECT ... FOR UPDATE
GET {{baseUrl}}/phantomRead/selectForUpdate
Content-Type: application/json


### 幻读测试 SELECT ... FOR UPDATE
GET {{baseUrl}}/phantomRead/selectForUpdateRange
Content-Type: application/json



### 幻读测试 SELECT ... LOCK IN SHARE MODE
GET {{baseUrl}}/phantomRead/selectForShare
Content-Type: application/json

### 当前读测试 插入数据
GET {{baseUrl}}/phantomRead/insertIntoTestData
Content-Type: application/json

### 当前读测试 修改数据
GET {{baseUrl}}/phantomRead/update
Content-Type: application/json

### 当前读测试 范围更新数据 触发间隙锁
GET {{baseUrl}}/phantomRead/updateByRange
Content-Type: application/json

### 当前读测试 范围删除数据 触发间隙锁
GET {{baseUrl}}/phantomRead/deleteByRange
Content-Type: application/json

### 锁范围与当前读区间不一致
GET {{baseUrl}}/phantomRead/deleteByRange1
Content-Type: application/json

### 当前读测试 插入数据
GET {{baseUrl}}/phantomRead/insert
Content-Type: application/json




